version: 2
jobs:
    build:
        docker:
            # specify the version you desire here
            - image: circleci/node:latest-browsers
        environment:
            NPM_CONFIG_LOGLEVEL: error
            JOBS: max # https://gist.github.com/ralphtheninja/f7c45bdee00784b41fed
        working_directory: ~/micro-app-plugin-vue-cli
        branches:
            ignore:
                - docs
                - gh-pages

        steps:
            - checkout
            - restore_cache:
                  key: micro-app-plugin-vue-cli-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - run: yarn --network-timeout 600000
            - save_cache:
                key: micro-app-plugin-vue-cli-{{ .Branch }}-{{ checksum "yarn.lock" }}
                paths:
                    - ./node_modules
            - run: yarn run test --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

